# Site Settings
title: Tejaswin Parthasarathy's Homepage
email: ##
description: >
        Tejaswin Parthasarathy's Homepage
baseurl: ""
url: "https://parthas1.github.io/"
github_username: parthas1
include: ['_sections']
plugins:
  - jekyll-seo-tag